name: Debian Package Build
on:
  pull_request:
    branches:
      - equuleus
    paths:
      - '**'
      - '!.github/**'
      - '!**/*.md'

jobs:
  package-build:
    runs-on: ubuntu-latest
    container:
      image: vyos/vyos-build:equuleus
      options: --sysctl net.ipv6.conf.lo.disable_ipv6=0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Debian package
        run: dpkg-buildpackage -uc -us -tc -b
