name: Trigger to build a deb package from repo

on:
  pull_request:
    types:
      - closed
    branches:
      - current
  workflow_dispatch:

jobs:
  trigger-build:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    env:
      REF: main  # Used for curl to trigger build package

    steps:
      - name: Set variables
        run: |
          echo "PACKAGE_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Trigger rebuild for ${{ env.PACKAGE_NAME }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ secrets.REMOTE_OWNER }}/${{ secrets.REMOTE_REUSE_REPO }}/actions/workflows/build-package.yml/dispatches \
            -d '{"ref": "${{ env.REF }}", "inputs":{"package_name":"'"$PACKAGE_NAME"'", "gpg_key_id": "${{ secrets.GPG_KEY_ID }}", "package_branch": "${{ github.ref_name }}"}}'
